import {CONFIG} from "./config.js";
const fleet=[
{id:"5T-01",type:"5 Ton",capacity:5,color:"#4ea1ff"},{id:"5T-02",type:"5 Ton",capacity:5,color:"#6d7cff"},{id:"5T-03",type:"5 Ton",capacity:5,color:"#9a72ff"},{id:"5T-04",type:"5 Ton",capacity:5,color:"#48c7d9"},
{id:"3T-01",type:"3 Ton",capacity:3,color:"#55c978"},{id:"3T-02",type:"3 Ton",capacity:3,color:"#9bd24f"},
{id:"VAN-01",type:"Sprinter",capacity:null,color:"#e7b84d"},{id:"VAN-02",type:"Sprinter",capacity:null,color:"#f08a4b"}];
let jobs=JSON.parse(localStorage.getItem("ms_jobs")||"[]");
document.querySelector("#app").innerHTML=`<header class="header"><div class="brand">Moulding Store<small>Premium Route Planner</small></div><div><button class="btn" id="export">Export</button> <button class="btn primary" id="opt">Optimize</button></div></header><main class="main"><aside class="side"><div class="stats"><div class="stat"><b id="jc">0</b><span>Deliveries</span></div><div class="stat"><b>8</b><span>Vehicles</span></div><div class="stat"><b id="ac">0</b><span>Assigned</span></div></div><section class="card"><b>Add Delivery</b><form id="form"><div class="grid"><div class="field"><label>Customer</label><input id="customer" required></div><div class="field"><label>Vehicle</label><select id="vehicle"><option>5 Ton</option><option>3 Ton</option><option>Sprinter</option></select></div><div class="field full"><label>Address</label><input id="address" required></div><div class="field"><label>Service minutes</label><input id="service" type="number" value="15" min="0"></div><div class="field"><label>Weight tons</label><input id="weight" type="number" step=".1" min="0"></div></div><button class="btn primary" style="width:100%">+ Save Delivery</button></form></section><section class="card"><div style="display:flex;justify-content:space-between"><b>Truck Routes</b><span class="muted">Drag & drop</span></div><div id="routes"></div></section></aside><section class="map"><div class="overlay"><div class="chip">5T × 4</div><div class="chip">3T × 2</div><div class="chip">Sprinter × 2</div></div><div id="map"></div></section></main>`;
const map=L.map("map").setView([51.0447,-114.0719],10);L.tileLayer(CONFIG.mapTiles,{attribution:CONFIG.mapAttribution}).addTo(map);let layers=[];
const save=()=>localStorage.setItem("ms_jobs",JSON.stringify(jobs));
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
document.querySelector("#form").onsubmit=e=>{e.preventDefault();jobs.push({id:crypto.randomUUID(),customer:customer.value.trim(),address:address.value.trim(),vehicle:vehicle.value,service:Number(service.value||15),weight:Number(weight.value||0),truckId:null,lat:null,lng:null});save();e.target.reset();service.value=15;render()};
document.querySelector("#opt").onclick=()=>{for(const type of ["5 Ton","3 Ton","Sprinter"]){let ts=fleet.filter(t=>t.type===type),list=jobs.filter(j=>j.vehicle===type);list.forEach((j,i)=>j.truckId=ts[i%ts.length].id)}save();render()};
document.querySelector("#export").onclick=()=>{let rows=[["ID","Customer","Address","Vehicle","Truck","Stop","ServiceMinutes","WeightTons"]];fleet.forEach(t=>jobs.filter(j=>j.truckId===t.id).forEach((j,i)=>rows.push([j.id,j.customer,j.address,j.vehicle,t.id,i+1,j.service,j.weight])));jobs.filter(j=>!j.truckId).forEach(j=>rows.push([j.id,j.customer,j.address,j.vehicle,"","",j.service,j.weight]));let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\\n")],{type:"text/csv"}));a.download="moulding-routes.csv";a.click()};
function render(){document.querySelector("#jc").textContent=jobs.length;document.querySelector("#ac").textContent=jobs.filter(j=>j.truckId).length;let root=document.querySelector("#routes");root.innerHTML="";fleet.forEach(t=>{let stops=jobs.filter(j=>j.truckId===t.id),el=document.createElement("div");el.className="truck";el.innerHTML=`<div class="truckhead"><div><b>🚚 ${t.id}</b><div class="muted">${t.type} • ${t.capacity?t.capacity+"T capacity":"Van"} • ${stops.length} stops</div></div><button class="btn" data-share="${t.id}">Share</button></div><div class="truckbody" data-truck="${t.id}"></div>`;let body=el.querySelector(".truckbody");body.ondragover=e=>{e.preventDefault();body.classList.add("over")};body.ondragleave=()=>body.classList.remove("over");body.ondrop=e=>{e.preventDefault();body.classList.remove("over");move(e.dataTransfer.getData("job"),t.id)};if(!stops.length)body.innerHTML='<div class="empty">Drop compatible job here</div>';stops.forEach((j,i)=>{let s=document.createElement("div");s.className="stop";s.draggable=true;s.innerHTML=`<div class="num">${i+1}</div><div class="info"><b>${esc(j.customer)}</b><span>${esc(j.address)}</span></div><span class="pill">${j.vehicle}</span>`;s.ondragstart=e=>e.dataTransfer.setData("job",j.id);body.appendChild(s)});root.appendChild(el)});root.querySelectorAll("[data-share]").forEach(b=>b.onclick=()=>share(b.dataset.share));drawMap()}
function move(id,tid){let j=jobs.find(x=>x.id===id),t=fleet.find(x=>x.id===tid);if(j&&t&&j.vehicle===t.type){j.truckId=tid;save();render()}}
async function geo(q){try{let r=await fetch(`${CONFIG.geocoder}?format=jsonv2&limit=1&q=${encodeURIComponent(q)}`),d=await r.json();return d[0]?{lat:+d[0].lat,lng:+d[0].lon}:null}catch{return null}}
async function drawMap(){layers.forEach(x=>map.removeLayer(x));layers=[];let all=[];for(const t of fleet){let stops=jobs.filter(j=>j.truckId===t.id),pts=[];for(let i=0;i<stops.length;i++){let j=stops[i];if(j.lat==null){let p=await geo(j.address);if(p){Object.assign(j,p);save()}}if(j.lat==null)continue;pts.push([j.lat,j.lng]);all.push([j.lat,j.lng]);let icon=L.divIcon({className:"",html:`<div class="map-marker" style="background:${t.color}">${i+1}</div>`,iconSize:[29,29],iconAnchor:[14,14]});layers.push(L.marker([j.lat,j.lng],{icon}).bindPopup(`<b>${esc(j.customer)}</b><br>${esc(j.address)}<br>${t.id}`).addTo(map))}if(pts.length>1){let line=L.polyline(pts,{color:t.color,weight:5,opacity:.8});line.on("mouseover",()=>line.setStyle({weight:10}));line.on("mouseout",()=>line.setStyle({weight:5}));layers.push(line.addTo(map))}}if(all.length)map.fitBounds(all,{padding:[35,35],maxZoom:13})}
async function share(id){let t=fleet.find(x=>x.id===id),stops=jobs.filter(j=>j.truckId===id);for(let j of stops)if(j.lat==null){let p=await geo(j.address);if(p)Object.assign(j,p)}let c=stops.filter(j=>j.lat!=null).map(j=>`${j.lat},${j.lng}`);if(!c.length)return alert("Could not geocode the route.");let u=`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(c[0])}&destination=${encodeURIComponent(c.at(-1))}&travelmode=driving`;if(c.length>2)u+=`&waypoints=${encodeURIComponent(c.slice(1,-1).join("|"))}`;if(navigator.share)navigator.share({title:t.id+" Route",url:u}).catch(()=>{});else navigator.clipboard.writeText(u).then(()=>alert("Google Maps link copied."))}
render();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});