import {CONFIG} from "./config.js";
const fleet=[
{id:"5T-01",type:"5 Ton",capacity:5,color:"#4ea1ff"},{id:"5T-02",type:"5 Ton",capacity:5,color:"#6d7cff"},{id:"5T-03",type:"5 Ton",capacity:5,color:"#9a72ff"},{id:"5T-04",type:"5 Ton",capacity:5,color:"#48c7d9"},
{id:"3T-01",type:"3 Ton",capacity:3,color:"#55c978"},{id:"3T-02",type:"3 Ton",capacity:3,color:"#9bd24f"},
{id:"VAN-01",type:"Sprinter",capacity:null,color:"#e7b84d"},{id:"VAN-02",type:"Sprinter",capacity:null,color:"#f08a4b"}];
let jobs=JSON.parse(localStorage.getItem("ms_jobs")||"[]");
document.querySelector("#app").innerHTML=`<header class="header"><div class="brand">Moulding Store<small>Premium Route Planner</small></div><div><button class="btn" id="export">Export</button> <button class="btn primary" id="opt">Optimize</button></div></header><main class="main"><aside class="side"><div class="stats"><div class="stat"><b id="jc">0</b><span>Deliveries</span></div><div class="stat"><b>8</b><span>Vehicles</span></div><div class="stat"><b id="ac">0</b><span>Assigned</span></div></div><section class="card"><b>Add Delivery</b><form id="form"><div class="grid"><div class="field"><label>Customer</label><input id="customer" required></div><div class="field"><label>Vehicle</label><select id="vehicle"><option>5 Ton</option><option>3 Ton</option><option>Sprinter</option></select></div><div class="field full"><label>Address</label><input id="address" required></div><div class="field"><label>Service minutes</label><input id="service" type="number" value="15" min="0"></div><div class="field"><label>Weight tons</label><input id="weight" type="number" step=".1" min="0"></div></div><button class="btn primary" style="width:100%">+ Save Delivery</button></form></section><section class="card"><div style="display:flex;justify-content:space-between"><b>Truck Routes</b><span class="muted">Drag & drop</span></div><div id="routes"></div></section></aside><section class="map"><div class="overlay"><div class="chip">5T × 4</div><div class="chip">3T × 2</div><div class="chip">Sprinter × 2</div></div><div id="map"></div></section></main>`;
const map=L.map("map").setView([51.0447,-114.0719],10);L.tileLayer(CONFIG.mapTiles,{attribution:CONFIG.mapAttribution}).addTo(map);let layers=[];
const save=()=>localStorage.setItem("ms_jobs",JSON.stringify(jobs));
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));

// No-API-key Alberta address autocomplete using Photon/OpenStreetMap.
// We deliberately require a house/building number + street and filter out
// city/street-only results so the dropdown is useful for deliveries.
const addressAC={timer:null,controller:null,results:[],active:-1};
function clearAddressSuggestions(){const box=document.querySelector("#address-suggestions");if(box){box.innerHTML="";box.classList.remove("show")}addressAC.results=[];addressAC.active=-1}
function renderAddressSuggestions(results){const box=document.querySelector("#address-suggestions");if(!box)return;box.innerHTML="";addressAC.results=results;addressAC.active=-1;if(!results.length){box.classList.remove("show");return}results.forEach((item,i)=>{const b=document.createElement("button");b.type="button";b.className="address-suggestion";b.setAttribute("role","option");b.dataset.index=i;const p=item.properties||{};const title=[p.housenumber,p.street||p.name].filter(Boolean).join(" ");const detail=[p.city||p.locality,p.state||p.province,p.postcode].filter(Boolean).join(", ");b.innerHTML=`<span class="address-suggestion-icon">⌖</span><span class="address-suggestion-copy"><strong>${esc(title||item.label||"")}</strong><small>${esc(detail)}</small></span>`;b.addEventListener("mousedown",e=>{e.preventDefault();selectAddressSuggestion(i)});box.appendChild(b)});box.classList.add("show")}
function photonFeatureToAddress(f){const p=f.properties||{};const coords=f.geometry&&f.geometry.coordinates||[];const label=f.properties&&f.properties.label||[p.housenumber,p.street||p.name,p.city||p.locality,p.state,p.postcode,p.country].filter(Boolean).join(", ");return {display_name:label,lat:Number(coords[1]),lon:Number(coords[0]),place_id:p.osm_id||p.osm_type||label,provider:"photon",photon:f}}
async function fetchAlbertaAddresses(q){
  if(!/\d/.test(q)) return [];
  if(addressAC.controller) addressAC.controller.abort();
  addressAC.controller=new AbortController();
  const params=new URLSearchParams({q:`${q}, Alberta, Canada`,limit:"12",lang:"en",bbox:CONFIG.geocoderBbox});
  const r=await fetch(`${CONFIG.geocoder}?${params}`,{signal:addressAC.controller.signal,headers:{Accept:"application/json"}});
  if(!r.ok)throw new Error("Address lookup failed");
  const data=await r.json();
  const features=Array.isArray(data.features)?data.features:[];
  return features.map(photonFeatureToAddress).filter(x=>{
    const p=x.photon?.properties||{};
    const country=String(p.countrycode||p.country_code||"").toLowerCase();
    const state=String(p.state||p.province||"").toLowerCase();
    const house=String(p.housenumber||"").trim();
    const street=String(p.street||p.name||"").trim();
    return (country==="ca"||String(p.country||"").toLowerCase()==="canada") &&
      (state==="alberta"||state==="ab") && !!house && !!street && Number.isFinite(x.lat) && Number.isFinite(x.lon);
  }).slice(0,8);
}
function selectAddressSuggestion(i){const item=addressAC.results[i];if(!item)return;const input=document.querySelector("#address");input.value=item.display_name||"";input.dataset.lat=item.lat||"";input.dataset.lng=item.lon||"";input.dataset.placeId=item.place_id||"";input.dataset.provider="photon";input.dataset.selected="1";clearAddressSuggestions()}
function setupAddressAutocomplete(){const input=document.querySelector("#address");if(!input)return;input.setAttribute("autocomplete","off");input.setAttribute("aria-autocomplete","list");input.setAttribute("placeholder","House number + street (e.g. 123 17 Ave SW)");input.parentElement.classList.add("address-autocomplete-wrap");const box=document.createElement("div");box.id="address-suggestions";box.className="address-suggestions";box.setAttribute("role","listbox");input.parentElement.appendChild(box);input.addEventListener("input",()=>{input.dataset.selected="";input.dataset.lat="";input.dataset.lng="";const q=input.value.trim();clearTimeout(addressAC.timer);if(q.length<3){clearAddressSuggestions();return}addressAC.timer=setTimeout(async()=>{try{renderAddressSuggestions(await fetchAlbertaAddresses(q))}catch(e){if(e.name!=="AbortError")clearAddressSuggestions()}},350)});input.addEventListener("keydown",e=>{if(!box.classList.contains("show")||!addressAC.results.length)return;if(e.key==="ArrowDown"){e.preventDefault();addressAC.active=Math.min(addressAC.active+1,addressAC.results.length-1)}else if(e.key==="ArrowUp"){e.preventDefault();addressAC.active=Math.max(addressAC.active-1,0)}else if(e.key==="Enter"&&addressAC.active>=0){e.preventDefault();selectAddressSuggestion(addressAC.active);return}else if(e.key==="Escape"){clearAddressSuggestions();return}else return;box.querySelectorAll(".address-suggestion").forEach((x,i)=>x.classList.toggle("active",i===addressAC.active))});document.addEventListener("click",e=>{if(!input.parentElement.contains(e.target))clearAddressSuggestions()})}
setupAddressAutocomplete();

document.querySelector("#form").onsubmit=e=>{e.preventDefault();const a=document.querySelector("#address");if(!a.dataset.selected || !/\d+/.test(a.value)){alert("Please select a complete Alberta street address from the suggestions, including the house number and street.");a.focus();return}jobs.push({id:crypto.randomUUID(),customer:customer.value.trim(),address:a.value.trim(),vehicle:vehicle.value,service:Number(service.value||15),weight:Number(weight.value||0),truckId:null,lat:a.dataset.lat?+a.dataset.lat:null,lng:a.dataset.lng?+a.dataset.lng:null});save();e.target.reset();service.value=15;render()};
document.querySelector("#opt").onclick=()=>{for(const type of ["5 Ton","3 Ton","Sprinter"]){let ts=fleet.filter(t=>t.type===type),list=jobs.filter(j=>j.vehicle===type);list.forEach((j,i)=>j.truckId=ts[i%ts.length].id)}save();render()};
document.querySelector("#export").onclick=()=>{let rows=[["ID","Customer","Address","Vehicle","Truck","Stop","ServiceMinutes","WeightTons"]];fleet.forEach(t=>jobs.filter(j=>j.truckId===t.id).forEach((j,i)=>rows.push([j.id,j.customer,j.address,j.vehicle,t.id,i+1,j.service,j.weight])));jobs.filter(j=>!j.truckId).forEach(j=>rows.push([j.id,j.customer,j.address,j.vehicle,"","",j.service,j.weight]));let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\\n")],{type:"text/csv"}));a.download="moulding-routes.csv";a.click()};
function render(){document.querySelector("#jc").textContent=jobs.length;document.querySelector("#ac").textContent=jobs.filter(j=>j.truckId).length;let root=document.querySelector("#routes");root.innerHTML="";fleet.forEach(t=>{let stops=jobs.filter(j=>j.truckId===t.id),el=document.createElement("div");el.className="truck";el.innerHTML=`<div class="truckhead"><div><b>🚚 ${t.id}</b><div class="muted">${t.type} • ${t.capacity?t.capacity+"T capacity":"Van"} • ${stops.length} stops</div></div><button class="btn" data-share="${t.id}">Share</button></div><div class="truckbody" data-truck="${t.id}"></div>`;let body=el.querySelector(".truckbody");body.ondragover=e=>{e.preventDefault();body.classList.add("over")};body.ondragleave=()=>body.classList.remove("over");body.ondrop=e=>{e.preventDefault();body.classList.remove("over");move(e.dataTransfer.getData("job"),t.id)};if(!stops.length)body.innerHTML='<div class="empty">Drop compatible job here</div>';stops.forEach((j,i)=>{let s=document.createElement("div");s.className="stop";s.draggable=true;s.innerHTML=`<div class="num">${i+1}</div><div class="info"><b>${esc(j.customer)}</b><span>${esc(j.address)}</span></div><span class="pill">${j.vehicle}</span>`;s.ondragstart=e=>e.dataTransfer.setData("job",j.id);body.appendChild(s)});root.appendChild(el)});root.querySelectorAll("[data-share]").forEach(b=>b.onclick=()=>share(b.dataset.share));drawMap()}
function move(id,tid){let j=jobs.find(x=>x.id===id),t=fleet.find(x=>x.id===tid);if(j&&t&&j.vehicle===t.type){j.truckId=tid;save();render()}}
async function geo(q){try{const params=new URLSearchParams({q:`${q}, Alberta, Canada`,limit:"5",lang:"en",bbox:CONFIG.geocoderBbox});const r=await fetch(`${CONFIG.geocoder}?${params}`,{headers:{Accept:"application/json"}});if(!r.ok)return null;const d=await r.json();const x=(d.features||[]).map(photonFeatureToAddress).find(v=>{const p=v.photon?.properties||{};const state=String(p.state||p.province||"").toLowerCase();const country=String(p.countrycode||p.country_code||p.country||"").toLowerCase();return (country==="ca"||country==="canada")&&(state==="alberta"||state==="ab")&&Number.isFinite(v.lat)&&Number.isFinite(v.lon)});return x?{lat:x.lat,lng:x.lon}:null}catch{return null}}
async function drawMap(){layers.forEach(x=>map.removeLayer(x));layers=[];let all=[];for(const t of fleet){let stops=jobs.filter(j=>j.truckId===t.id),pts=[];for(let i=0;i<stops.length;i++){let j=stops[i];if(j.lat==null){let p=await geo(j.address);if(p){Object.assign(j,p);save()}}if(j.lat==null)continue;pts.push([j.lat,j.lng]);all.push([j.lat,j.lng]);let icon=L.divIcon({className:"",html:`<div class="map-marker" style="background:${t.color}">${i+1}</div>`,iconSize:[29,29],iconAnchor:[14,14]});layers.push(L.marker([j.lat,j.lng],{icon}).bindPopup(`<b>${esc(j.customer)}</b><br>${esc(j.address)}<br>${t.id}`).addTo(map))}if(pts.length>1){let line=L.polyline(pts,{color:t.color,weight:5,opacity:.8});line.on("mouseover",()=>line.setStyle({weight:10}));line.on("mouseout",()=>line.setStyle({weight:5}));layers.push(line.addTo(map))}}if(all.length)map.fitBounds(all,{padding:[35,35],maxZoom:13})}
async function share(id){let t=fleet.find(x=>x.id===id),stops=jobs.filter(j=>j.truckId===id);for(let j of stops)if(j.lat==null){let p=await geo(j.address);if(p)Object.assign(j,p)}let c=stops.filter(j=>j.lat!=null).map(j=>`${j.lat},${j.lng}`);if(!c.length)return alert("Could not geocode the route.");let u=`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(c[0])}&destination=${encodeURIComponent(c.at(-1))}&travelmode=driving`;if(c.length>2)u+=`&waypoints=${encodeURIComponent(c.slice(1,-1).join("|"))}`;if(navigator.share)navigator.share({title:t.id+" Route",url:u}).catch(()=>{});else navigator.clipboard.writeText(u).then(()=>alert("Google Maps link copied."))}
render();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});